stages:
  - Build

ros1:
  stage: Build
  trigger:
    include: tests/ros1/.gitlab-ci.yml
    strategy: depend

ros2:
  stage: Build
  trigger:
    include: tests/ros2/.gitlab-ci.yml
    strategy: depend
