stages:
  - Test

default:
  image: badouralix/curl-jq

trigger:
  stage: Test
  script:
    - mkdir artifacts
    - curl --silent --fail --request POST --form token=$DOCKER_ROS_CI_TRIGGER_TOKEN --form ref=main --form "variables[DOCKER_ROS_GIT_REF]=$CI_COMMIT_SHA" "https://gitlab.ika.rwth-aachen.de/api/v4/projects/1886/trigger/pipeline" | jq -r .id > artifacts/id
  artifacts:
    paths: [artifacts]
    expire_in: 1h

monitor:
  stage: Test
  needs: [trigger]
  script:
    - PIPELINE_ID=$(cat artifacts/id)
    - |-
      while true; do
        sleep 30
        PIPELINE_STATUS=$(curl --silent --header "PRIVATE-TOKEN: $DOCKER_ROS_CI_READ_PIPELINE_TOKEN" "https://gitlab.ika.rwth-aachen.de/api/v4/projects/1886/pipelines/$PIPELINE_ID" | jq -r .status)
        echo "Pipeline status: $PIPELINE_STATUS (https://gitlab.ika.rwth-aachen.de/fb-fi/ops/docker-ros-ci/-/pipelines/$PIPELINE_ID)"
        if [[ $PIPELINE_STATUS == "success" ]]; then
          break
        elif [[ $PIPELINE_STATUS == "failed" ]]; then
          exit 1
        elif [[ $PIPELINE_STATUS == "canceled" ]]; then
          exit 1
        fi
      done
