default:
  image: docker:20.10.22-git
  services:
    - docker:20.10.22-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd $DOCKER_COMPOSE_DIR
    - 'sed -i "/\ image:/a\    platform: $PLATFORM" docker-compose.yaml'


variables:
  IMAGE_DEVEL:          gitlab.ika.rwth-aachen.de:5050/${CI_PROJECT_PATH}:latest-dev
  IMAGE_RUN:            gitlab.ika.rwth-aachen.de:5050/${CI_PROJECT_PATH}:latest
  IMAGE_DEVEL_CI_AMD64: ${IMAGE_DEVEL}_ci-amd64
  IMAGE_DEVEL_CI_ARM64: ${IMAGE_DEVEL}_ci-arm64
  IMAGE_RUN_CI_AMD64:   ${IMAGE_RUN}_ci-amd64
  IMAGE_RUN_CI_ARM64:   ${IMAGE_RUN}_ci-arm64
  DOCKER_COMPOSE_DIR: docker
  ROS_WORKSPACE_DIR: .
  GIT_HTTPS_USER: gitlab-ci-token
  GIT_HTTPS_PASSWORD: $CI_JOB_TOKEN
  # -----
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_BUILDKIT: 1


stages:
  - Build Images (amd64)
  - Build Images (arm64)
  - ROS Industrial CI
  - Push Images


devel-amd64:
  stage: Build Images (amd64)
  script:
    - docker compose build devel
    - docker tag $IMAGE_DEVEL $IMAGE_DEVEL_CI_AMD64
    - docker push $IMAGE_DEVEL_CI_AMD64
  variables:
    PLATFORM: linux/amd64

run-amd64:
  stage: Build Images (amd64)
  script:
    - docker compose build run
    - docker tag $IMAGE_RUN $IMAGE_RUN_CI_AMD64
    - docker push $IMAGE_RUN_CI_AMD64
  variables:
    PLATFORM: linux/amd64


devel-arm64:
  stage: Build Images (arm64)
  script:
    - docker compose build devel
    - docker tag $IMAGE_DEVEL $IMAGE_DEVEL_CI_ARM64
    - docker push $IMAGE_DEVEL_CI_ARM64
  variables:
    PLATFORM: linux/arm64

run-arm64:
  stage: Build Images (arm64)
  script:
    - docker compose build run
    - docker tag $IMAGE_RUN $IMAGE_RUN_CI_ARM64
    - docker push $IMAGE_RUN_CI_ARM64
  variables:
    PLATFORM: linux/arm64


Test devel-amd64:
  stage: ROS Industrial CI
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update bash coreutils grep tar
    - git clone --branch master --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
    - test -f .repos || echo "repositories:" > .repos
  script: .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: noetic
    BUILDER: catkin_tools
    UPSTREAM_WORKSPACE: $ROS_WORKSPACE_DIR/.repos
    TARGET_WORKSPACE: $ROS_WORKSPACE_DIR
    CATKIN_LINT: 'true'
    ADDITIONAL_DEBS: git
    BEFORE_INIT_EMBED: git config --global url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}.insteadOf ${CI_SERVER_URL}
    DOCKER_IMAGE: $IMAGE_DEVEL_CI_AMD64
    DOCKER_RUN_OPTS: -u root:root


Push devel:
  stage: Push Images
  only: [main]
  needs: [devel-amd64, devel-arm64, Test devel-amd64]
  script:
    - docker manifest create $IMAGE_DEVEL --amend $IMAGE_DEVEL_CI_AMD64 --amend $IMAGE_DEVEL_CI_ARM64
    - docker manifest push $IMAGE_DEVEL

Push run:
  stage: Push Images
  only: [main]
  needs: [run-amd64, run-arm64, Test devel-amd64]
  script:
    - docker manifest create $IMAGE_RUN --amend $IMAGE_RUN_CI_AMD64 --amend $IMAGE_RUN_CI_ARM64
    - docker manifest push $IMAGE_RUN
