workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG


variables:
  IMAGE_DEV:            gitlab.ika.rwth-aachen.de:5050/${CI_PROJECT_PATH}:latest-dev
  IMAGE_RUN:            gitlab.ika.rwth-aachen.de:5050/${CI_PROJECT_PATH}:latest
  IMAGE_DEV_CI_AMD64:   ${IMAGE_DEV}_${CI_COMMIT_REF_SLUG}_ci-amd64
  IMAGE_DEV_CI_ARM64:   ${IMAGE_DEV}_${CI_COMMIT_REF_SLUG}_ci-arm64
  IMAGE_RUN_CI_AMD64:   ${IMAGE_RUN}_${CI_COMMIT_REF_SLUG}_ci-amd64
  IMAGE_RUN_CI_ARM64:   ${IMAGE_RUN}_${CI_COMMIT_REF_SLUG}_ci-arm64
  IMAGE_CACHE:          ${IMAGE_DEV}
  DOCKER_COMPOSE_DIR: docker
  ROS_WORKSPACE_DIR: .
  DISABLE_INDUSTRIAL_CI: 'false'
  GIT_HTTPS_USER: gitlab-ci-token
  GIT_HTTPS_PASSWORD: $CI_JOB_TOKEN
  # -----
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_BUILDKIT: 1


stages:
  - Build Images (amd64)
  - Build Images (arm64)
  - ROS Industrial CI
  - Push Images


default:
  image: docker:20.10.22-git
  services:
    - docker:20.10.22-dind
  tags:
    - privileged
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create buildx-context
    - docker buildx create --use buildx-context
    - cd $DOCKER_COMPOSE_DIR
    - 'sed -i "/\    image:/a\    platform: $PLATFORM" docker-compose.yaml'
    - 'sed -i "/\  context:/a\  cache_from: [$IMAGE_CACHE]\n\  cache_to: [type=inline]" docker-compose.yaml'


dev-amd64:
  stage: Build Images (amd64)
  script:
    - docker compose build dev
    - docker tag $IMAGE_DEV $IMAGE_DEV_CI_AMD64
    - docker push $IMAGE_DEV_CI_AMD64
  variables:
    PLATFORM: linux/amd64
    IMAGE_CACHE: $IMAGE_DEV_CI_AMD64

run-amd64:
  stage: Build Images (amd64)
  script:
    - docker compose build run
    - docker tag $IMAGE_RUN $IMAGE_RUN_CI_AMD64
    - docker push $IMAGE_RUN_CI_AMD64
  variables:
    PLATFORM: linux/amd64
    IMAGE_CACHE: $IMAGE_RUN_CI_AMD64


dev-arm64:
  stage: Build Images (arm64)
  script:
    - docker compose build dev
    - docker tag $IMAGE_DEV $IMAGE_DEV_CI_ARM64
    - docker push $IMAGE_DEV_CI_ARM64
  variables:
    PLATFORM: linux/arm64
    IMAGE_CACHE: $IMAGE_DEV_CI_ARM64

run-arm64:
  stage: Build Images (arm64)
  script:
    - docker compose build run
    - docker tag $IMAGE_RUN $IMAGE_RUN_CI_ARM64
    - docker push $IMAGE_RUN_CI_ARM64
  variables:
    PLATFORM: linux/arm64
    IMAGE_CACHE: $IMAGE_RUN_CI_ARM64


Test dev-amd64:
  stage: ROS Industrial CI
  rules:
    - if: $DISABLE_INDUSTRIAL_CI != 'true'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update bash coreutils grep tar
    - git clone --branch master --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
    - test -f .repos || echo "repositories:" > .repos
  script: .industrial_ci/gitlab.sh
  variables:
    UPSTREAM_WORKSPACE: $ROS_WORKSPACE_DIR/.repos
    TARGET_WORKSPACE: $ROS_WORKSPACE_DIR
    ADDITIONAL_DEBS: git
    BEFORE_INIT_EMBED: git config --global url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}.insteadOf ${CI_SERVER_URL}
    DOCKER_IMAGE: $IMAGE_DEV_CI_AMD64
    DOCKER_RUN_OPTS: -u root:root


Push dev:
  stage: Push Images
  only: [main]
  needs:
    - dev-amd64
    - dev-arm64
    - job: Test dev-amd64
      optional: true
  script:
    - docker manifest create $IMAGE_DEV --amend $IMAGE_DEV_CI_AMD64 --amend $IMAGE_DEV_CI_ARM64
    - docker manifest push $IMAGE_DEV

Push run:
  stage: Push Images
  only: [main]
  needs:
    - run-amd64
    - run-arm64
    - job: Test dev-amd64
      optional: true
  script:
    - docker manifest create $IMAGE_RUN --amend $IMAGE_RUN_CI_AMD64 --amend $IMAGE_RUN_CI_ARM64
    - docker manifest push $IMAGE_RUN
