# action.yml
name: 'Hello World'
description: 'Greet someone'
# TODO: move env (not supported) to inputs?
env:
  DOCKER_COMPOSE_DIR: docker
  DOCKER_COMPOSE_FILE: docker-compose.yml
inputs:
  token:
    description: 'access token for cloning docker-ros'
    required: true
    default: ''
  docker-registry:
    description: 'docker registry'
    required: false
    default: ghcr.io
  docker-registry-username:
    description: 'docker registry username'
    required: false
    default: ${{ github.actor }}
  docker-registry-password:
    description: 'docker registry username'
    required: false
    default: ${{ github.token }}
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: slugify-ref-name
      uses: gacts/github-slug@v1
      with:
        to-slug: ${{ github.ref_name }}
    - name: checkout code 
      uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-registry-username }}
        password: ${{ inputs.docker-registry-password }}
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2
    - name: checkout docker-ros 
      uses: actions/checkout@v3
      with:
        repository: ika-rwth-aachen/docker-ros
        token: ${{ inputs.token }}
        path: ${{ env.DOCKER_COMPOSE_DIR }}/docker-ros
    - name: docker build dev
      uses: ika-rwth-aachen/docker-ros/.github/actions/docker-build@feature/github-action
      with:
        platform: amd64
        target: dev
        target-image: ghcr.io/${{ github.repository }}:latest-dev
        image-name: ghcr.io/${{ github.repository }}:latest-dev_${{ steps.slugify-ref-name.outputs.slug }}_ci-amd64
    - name: docker build run
      uses: ika-rwth-aachen/docker-ros/.github/actions/docker-build@feature/github-action
      with:
        platform: amd64
        target: run
        target-image: ghcr.io/${{ github.repository }}:latest
        image-name: ghcr.io/${{ github.repository }}:latest_${{ steps.slugify-ref-name.outputs.slug }}_ci-amd64
