name: "docker-ros"
description: "docker-ros automatically builds development and deployment Docker images for your ROS-based repositories."

inputs:

  docker-ros-ref:
    description: "Ref of docker-ros"
    default: main

  target:
    description: "Target stage of Dockerfile (comma-separated list) [dev|run]"
    default: run
  
  platform:
    description: "Target platform architecture (comma-separated list) [amd64|arm64|...]"
  
  base-image:
    description: "Base image name:tag"
    required: true
  
  command:
    description: "Launch command of run image (required if target=run)"
  
  image:
    description: "Image name:tag of run image"
    default: ghcr.io/${{ github.repository }}:latest

  dev-image:
    description: "Image name:tag of dev image"

  build-context:
    description: "Build context of Docker build process"
    default: ${{ github.workspace }}

  registry: # TODO: infer from image name
    description: "Docker registry to push images to"
    default: ghcr.io

  registry-username:
    description: "Docker registry username"
    default: ${{ github.actor }}

  registry-password:
    description: "Docker registry password"
    default: ${{ github.token }}

  enable-industrial-ci:
    description: "Enable industrial_ci"
    default: false


runs:
  using: "composite"
  steps:

    - name: Slugify ref name
      id: slugify-ref-name
      uses: gacts/github-slug@v1
      with:
        to-slug: ${{ github.ref_name }}

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout docker-ros # TODO: only if not included as submodule
      uses: actions/checkout@v3
      with:
        repository: ika-rwth-aachen/docker-ros
        ref: ${{ inputs.docker-ros-ref }} # TODO: could be identified by the action ref
        path: ${{ inputs.build-context }}/docker/docker-ros # TODO: reative to github.workspace?

    - name: Get runner architecture
      id: get-runner-arch
      run: echo "RUNNER_ARCH = $(dpkg --print-architecture)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up QEMU for architecture emulation
      if: ${{ !contains(inputs.platform, steps.get-runner-arch.outputs.RUNNER_ARCH) }}
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build images
      id: build-images
      working-directory: ${{ inputs.build-context }}
      shell: bash
      run: docker/docker-ros/scripts/ci.sh
      env:
        PLATFORM: ${{ inputs.platform }}
        TARGET: ${{ inputs.target }}
        BASE_IMAGE: ${{ inputs.base-image }}
        COMMAND: ${{ inputs.command }}
        IMAGE: ${{ inputs.image }}
        DEV_IMAGE: ${{ inputs.dev-image }}

    - name: Set up industrial_ci
      shell: bash
      run: test -f ${{ inputs.build-context }}/.repos || echo "repositories:" > ${{ inputs.build-context }}/.repos

    - name: Run industrial_ci
      uses: ros-industrial/industrial_ci@master
      if: ${{ inputs.enable-industrial-ci == 'true' }}
      env:
        UPSTREAM_WORKSPACE: ${{ inputs.build-context }}/.repos
        TARGET_WORKSPACE: ${{ inputs.build-context }}
        ADDITIONAL_DEBS: git # TODO AFTER_INIT_EMBED: git config --global url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}.insteadOf ${CI_SERVER_URL}
        DOCKER_RUN_OPTS: -u root:root
        DOCKER_IMAGE: ${{ steps.build-images.outputs.INDUSTRIAL_CI_IMAGE }}
        DOCKER_PULL: false

    - name: Push images
      working-directory: ${{ inputs.build-context }}
      shell: bash
      run: docker/docker-ros/scripts/ci.sh
      env:
        PLATFORM: ${{ inputs.platform }}
        TARGET: ${{ inputs.target }}
        BASE_IMAGE: ${{ inputs.base-image }}
        COMMAND: ${{ inputs.command }}
        IMAGE: ${{ inputs.image }}
        DEV_IMAGE: ${{ inputs.dev-image }}
        _ENABLE_IMAGE_PUSH: true
        _ENABLE_MULTIARCH_BUILD: true
        _IMAGE_POSTFIX: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && format('_{0}_ci', steps.slugify-ref-name.outputs.slug) || '' }}
