# action.yml
name: 'Hello World'
description: 'Greet someone'
inputs:
  docker-compose-file:
    description: 'docker-compose-file'
    required: false
    default: 'docker-compose.yaml'
  docker-compose-dir:
    description: 'docker-compose-dir'
    required: false
    default: 'docker'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: checkout code 
      uses: actions/checkout@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2
    - name: docker build
      run: docker compose -f ${{ inputs.docker-compose-dir }}/${{ inputs.docker-compose-file }} build ${TARGET}
      shell: bash