# action.yml
name: 'Hello World'
description: 'Greet someone'
env:
  DOCKER_COMPOSE_DIR: docker
  DOCKER_COMPOSE_FILE: docker-compose.yml
inputs:
  token:
    description: 'access token for cloning docker-ros'
    required: true
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: checkout code 
      uses: actions/checkout@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2
    - name: checkout docker-ros 
      uses: actions/checkout@v3
      with:
        repository: ika-rwth-aachen/docker-ros
        token: ${{ inputs.token }}
        path: ${{ inputs.docker-compose-dir }}/docker-ros
    - name: docker build dev
      uses: ./.github/actions/docker-build.yml
      with:
        platform: amd64
        target: dev
        target-image: ghcr.io/$GIHUB_REPOSITORY:latest-dev
        image-name: ghcr.io/${GIHUB_REPOSITORY}_ci-amd64-dev
    - name: docker build run
      uses: ./.github/actions/docker-build.yml
      with:
        platform: amd64
        target: run
        target-image: ghcr.io/$GIHUB_REPOSITORY:latest
        image-name: ghcr.io/${GIHUB_REPOSITORY}_ci-amd64