x-base-image:   &base-image   $BASE_IMAGE  # e.g. gitlab.ika.rwth-aachen.de:5050/automated-driving/docker/ros1:noetic
x-devel-image:  &devel-image  $DEVEL_IMAGE # e.g. gitlab.ika.rwth-aachen.de:5050/ops/roscore:latest-dev
x-run-image:    &run-image    $RUN_IMAGE   # e.g. gitlab.ika.rwth-aachen.de:5050/ops/roscore:latest
x-command:      &command      $COMMAND     # e.g. roscore

# ==============================================================================

x-build: &build
  dockerfile: ./docker/docker-ros/Dockerfile
  context: ../
  cache_from: [$CACHE_IMAGE]
  cache_to: [type=inline]
  args:
    BASE_IMAGE: *base-image
    COMMAND: *command
    GIT_HTTPS_USER: $GIT_HTTPS_USER
    GIT_HTTPS_PASSWORD: $GIT_HTTPS_PASSWORD

services:
  devel:
    image: *devel-image
    build:
      target: development
      <<: *build
  run:
    image: *run-image
    build:
      target: run
      <<: *build