name: 'Docker build'
description: 'Docker build action'

inputs:
  platform:
    description: 'target platform (e.g. amd64 / arm64)'
    required: true
  target:
    description: 'docker target stage'
    required: true
  target-image:
    description: 'image name in compose file'
    required: true
  image-name:
    description: 'image name'
    required: true
  image-cache:
    description: 'image to cache from'
    required: false
    default: ${{ inputs.image-name }}
runs:
  using: "composite"
  steps:
    - name: checkout code 
      uses: actions/checkout@v3
    - name: docker build
      run: docker compose -f $DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_FILE build ${{ inputs.target }}
      shell: bash
    - name: docker tag
      run: docker tag ${{ inputs.target-image }} ${{ inputs.image-name }}
    - name: docker push
      run: docker push ${{ inputs.image-name }}