name: 'Docker build'
description: 'Docker build action'

# TODO: document somewhere?
# required envvars
#   PLATFORM
#   TARGET
#   BASE_IMAGE
#   IMAGE
#   COMMAND
  
runs:
  using: "composite"
  steps:

    - name: docker build
      run: ${DOCKER_DIR}/docker-ros/build.sh
      shell: bash

    - name: docker push
      run: docker push ${IMAGE}
      shell: bash
