name: 'Docker build'
description: 'Docker build action'

# TODO: document somewhere?
# required envvars
#   PLATFORM
#   TARGET
#   BASE_IMAGE
#   IMAGE
#   COMMAND
#   ROS_DIR
#   DOCKER_DIR
  
runs:
  using: "composite"
  steps:

    - name: docker build
      run: cd ${ROS_DIR} && ${GITHUB_WORKSPACE}/${DOCKER_DIR}/docker-ros/build.sh
      shell: bash
