workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"      # run child pipeline if triggered by parent pipeline
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # run merge request pipeline if triggered by merge request
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS  # don't run branch pipeline if open merge request exists
      when: never
    - if: $CI_COMMIT_BRANCH                             # run branch pipeline if triggered by commit
    - if: $CI_COMMIT_TAG                                # run tag pipeline with specific image tags if triggered by tag


variables:
  IMAGE_DEV_TARGET:     ${CI_REGISTRY_IMAGE}:latest-dev
  IMAGE_RUN_TARGET:     ${CI_REGISTRY_IMAGE}:latest
  IMAGE_DEV_CI:         ${IMAGE_DEV_TARGET}_${CI_COMMIT_REF_SLUG}_ci
  IMAGE_RUN_CI:         ${IMAGE_RUN_TARGET}_${CI_COMMIT_REF_SLUG}_ci
  IMAGE_DEV_CI_AMD64:   ${IMAGE_DEV_CI}-amd64
  IMAGE_DEV_CI_ARM64:   ${IMAGE_DEV_CI}-arm64
  IMAGE_RUN_CI_AMD64:   ${IMAGE_RUN_CI}-amd64
  IMAGE_RUN_CI_ARM64:   ${IMAGE_RUN_CI}-arm64
  IMAGE_DEV_LATEST:     ${CI_REGISTRY_IMAGE}:latest-dev
  IMAGE_RUN_LATEST:     ${CI_REGISTRY_IMAGE}:latest
  IMAGE_DEV_TARGET_TAG: ${IMAGE_DEV_TARGET}-${CI_COMMIT_TAG}-dev
  IMAGE_RUN_TARGET_TAG: ${IMAGE_RUN_TARGET}-${CI_COMMIT_TAG}
  IMAGE_DEV_TAG:        ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-dev
  IMAGE_RUN_TAG:        ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  PUSH_AS_LATEST:       'false'
  # -----
  DOCKER_ROS_GIT_REF: main
  DOCKER_COMPOSE_DIR: docker
  DOCKER_COMPOSE_FILE: docker-compose.yml
  ROS_DIR: .
  DISABLE_ARCH_AMD64: 'false'
  DISABLE_ARCH_ARM64: 'false'
  DISABLE_INDUSTRIAL_CI: 'false'
  DISABLE_PUSH: 'false'
  GIT_HTTPS_USER: gitlab-ci-token
  GIT_HTTPS_PASSWORD: $CI_JOB_TOKEN
  # -----
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_BUILDKIT: 1


stages:
  - Build dev Images
  - Build run Images
  - Test ROS Industrial CI
  - Push Multi-Arch Images


default:
  image: docker:20.10.22-git
  services:
    - docker:20.10.22-dind
  tags:
    - privileged
    - amd64
  before_script:
    - |-
      if [[ ! -d $DOCKER_COMPOSE_DIR/docker-ros ]]; then
        git config --global url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}.insteadOf ${CI_SERVER_URL}
        git clone --depth=1 https://gitlab.ika.rwth-aachen.de/fb-fi/ops/docker-ros.git $DOCKER_COMPOSE_DIR/docker-ros
        cd $DOCKER_COMPOSE_DIR/docker-ros
        git fetch origin $DOCKER_ROS_GIT_REF
        git checkout FETCH_HEAD
        cd -
      fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create buildx-context
    - docker buildx create --use buildx-context
    - cd $DOCKER_COMPOSE_DIR
    - ln -s $(echo "${DOCKER_COMPOSE_FILE%.*}").yml ${DOCKER_COMPOSE_FILE} 2> /dev/null || true
    - ln -s $(echo "${DOCKER_COMPOSE_FILE%.*}").yaml ${DOCKER_COMPOSE_FILE} 2> /dev/null || true
    - 'sed -i "/\    image:/a\    platform: $PLATFORM" $DOCKER_COMPOSE_FILE'
    - 'sed -i "/\  context:/a\  cache_from: [$IMG_CACHE]\n\  cache_to: [type=inline]" $DOCKER_COMPOSE_FILE'


.build:
  script:
    - docker compose -f $DOCKER_COMPOSE_FILE build ${TARGET}
    - docker tag ${IMG_TARGET} ${IMG}
    - docker push ${IMG}

dev-amd64:
  stage: Build dev Images
  extends: .build
  rules:
    - if: $DISABLE_ARCH_AMD64 != 'true'
  variables:
    PLATFORM: linux/amd64
    TARGET: dev
    IMG_TARGET: ${IMAGE_DEV_TARGET}
    IMG_CACHE: ${IMAGE_DEV_CI_AMD64}
    IMG: ${IMAGE_DEV_CI_AMD64}

dev-arm64:
  stage: Build dev Images
  extends: .build
  tags: [privileged, arm64]
  rules:
    - if: $DISABLE_ARCH_ARM64 != 'true'
  variables:
    PLATFORM: linux/arm64
    TARGET: dev
    IMG_TARGET: ${IMAGE_DEV_TARGET}
    IMG_CACHE: ${IMAGE_DEV_CI_ARM64}
    IMG: ${IMAGE_DEV_CI_ARM64}

run-amd64:
  stage: Build run Images
  extends: .build
  needs: [dev-amd64]
  rules:
    - if: $DISABLE_ARCH_AMD64 != 'true'
  variables:
    PLATFORM: linux/amd64
    TARGET: run
    IMG_TARGET: ${IMAGE_RUN_TARGET}
    IMG_CACHE: ${IMAGE_DEV_CI_AMD64}
    IMG: ${IMAGE_RUN_CI_AMD64}

run-arm64:
  stage: Build run Images
  extends: .build
  tags: [privileged, arm64]
  needs: [dev-arm64]
  rules:
    - if: $DISABLE_ARCH_ARM64 != 'true'
  variables:
    PLATFORM: linux/arm64
    TARGET: run
    IMG_TARGET: ${IMAGE_RUN_TARGET}
    IMG_CACHE: ${IMAGE_DEV_CI_ARM64}
    IMG: ${IMAGE_RUN_CI_ARM64}


.test:
  variables:
    UPSTREAM_WORKSPACE: $ROS_DIR/.repos
    TARGET_WORKSPACE: $ROS_DIR
    ADDITIONAL_DEBS: git
    AFTER_INIT_EMBED: git config --global url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}.insteadOf ${CI_SERVER_URL}
    DOCKER_RUN_OPTS: -u root:root
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update bash coreutils grep tar
    - git clone --branch master --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
    - test -f $ROS_DIR/.repos || echo "repositories:" > $ROS_DIR/.repos
  script: .industrial_ci/gitlab.sh

Test dev-amd64:
  stage: Test ROS Industrial CI
  extends: .test
  needs:
    - job: dev-amd64
      optional: true
  rules:
    - if: $DISABLE_INDUSTRIAL_CI != 'true' && $DISABLE_ARCH_AMD64 != 'true'
  variables:
    DOCKER_IMAGE: ${IMAGE_DEV_CI_AMD64}

Test dev-arm64:
  stage: Test ROS Industrial CI
  extends: .test
  tags: [privileged, arm64]
  needs:
    - job: dev-arm64
      optional: true
  rules:
      - if: $DISABLE_INDUSTRIAL_CI != 'true' && $DISABLE_ARCH_ARM64 != 'true'
  variables:
    DOCKER_IMAGE: ${IMAGE_DEV_CI_ARM64}


.push:
  needs:
    - job: dev-amd64
      optional: true
    - job: dev-arm64
      optional: true
    - job: run-amd64
      optional: true
    - job: run-arm64
      optional: true
    - job: Test dev-amd64
      optional: true
    - job: Test dev-arm64
      optional: true
  rules:
    - if: $DISABLE_PUSH == 'true' || $DISABLE_ARCH_AMD64 == 'true' && $DISABLE_ARCH_ARM64 == 'true'
      when: never
  script:
    - if [ $DISABLE_ARCH_AMD64 != "true" ] && [ $DISABLE_ARCH_ARM64 != "true" ]; then docker manifest create ${IMG_DEV} --amend ${IMAGE_DEV_CI_AMD64} --amend ${IMAGE_DEV_CI_ARM64} && docker manifest create ${IMG_RUN} --amend ${IMAGE_RUN_CI_AMD64} --amend ${IMAGE_RUN_CI_ARM64}; fi
    - if [ $DISABLE_ARCH_AMD64 != "true" ] && [ $DISABLE_ARCH_ARM64 = "true" ]; then docker manifest create ${IMG_DEV} --amend ${IMAGE_DEV_CI_AMD64} && docker manifest create ${IMG_RUN} --amend ${IMAGE_RUN_CI_AMD64}; fi
    - if [ $DISABLE_ARCH_AMD64 = "true" ] && [ $DISABLE_ARCH_ARM64 != "true" ]; then docker manifest create ${IMG_DEV} --amend ${IMAGE_DEV_CI_ARM64} && docker manifest create ${IMG_RUN} --amend ${IMAGE_RUN_CI_ARM64}; fi
    - docker manifest push ${IMG_DEV}
    - docker manifest push ${IMG_RUN}

Push CI:
  stage: Push Multi-Arch Images
  extends: .push
  rules:
    - !reference [.push, rules]
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  variables:
    IMG_DEV: ${IMAGE_DEV_CI}
    IMG_RUN: ${IMAGE_RUN_CI}

Push:
  stage: Push Multi-Arch Images
  extends: .push
  rules:
    - !reference [.push, rules]
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    IMG_DEV: ${IMAGE_DEV_TARGET}
    IMG_RUN: ${IMAGE_RUN_TARGET}

Push latest:
  stage: Push Multi-Arch Images
  extends: .push
  rules:
    - !reference [.push, rules]
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $PUSH_AS_LATEST == 'true'
  variables:
    IMG_DEV: ${IMAGE_DEV_LATEST}
    IMG_RUN: ${IMAGE_RUN_LATEST}

Push target tag:
  stage: Push Multi-Arch Images
  extends: .push
  rules:
    - !reference [.push, rules]
    - if: $CI_COMMIT_TAG
  variables:
    IMG_DEV: ${IMAGE_DEV_TARGET_TAG}
    IMG_RUN: ${IMAGE_RUN_TARGET_TAG}

Push tag:
  stage: Push Multi-Arch Images
  extends: .push
  rules:
    - !reference [.push, rules]
    - if: $CI_COMMIT_TAG && $PUSH_AS_LATEST == 'true'
  variables:
    IMG_DEV: ${IMAGE_DEV_TAG}
    IMG_RUN: ${IMAGE_RUN_TAG}
