on: [push]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Other Repository Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}  # Personal Access Token with appropriate permissions
          repository: ika-rwth-aachen/docker-ros-ci
          event-type: my-event
          client-payload: '{"ref": "feature/github-workflow"}'