on: [push]

jobs:
  trigger_workflow:
    name: Trigger docker-ros-ci workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow and Wait
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ika-rwth-aachen
          repo: docker-ros-ci
          ref: feature/github-workflow
          workflow_file_name: main.yml
          github_token: ${{ secrets.PAT }}  # Personal Access Token with appropriate permissions
          client_payload: '{"docker-ros-git-ref": "${{ github.ref_name }}"}'